sonar.projectKey=tw-core-api
sonar.projectName=tw-core-api
sonar.sources=src
sonar.tests=tests
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.test.inclusions=tests/**/*.test.ts
sonar.exclusions=**/node_modules/**,dist/**
